name: GitHub Actions Secret

on:
    push:
        branches: [main]

jobs:
    secrets-in-github-actions:
        steps:
            - name: Declare variables
              env:
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
